
CREATE TABLE `profil` (
  `ID` int(11) AUTO_INCREMENT PRIMARY KEY,
  `NAME` varchar(250) NOT NULL,
  `BIRTH` date NOT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `PASSWORD` text NOT NULL,
  `STAT` int(11) NOT NULL,
  `CURSUS` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

